{% set VERSION_SUFFIX = "" %} # debug version suffix, appended to the version

package:
  name: t2bc
  # GIT_DESCRIBE_TAG may not be set
  version: {{ "%s%s" % (environ.get('GIT_DESCRIBE_TAG', '').lstrip('v'), VERSION_SUFFIX) }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_{{ target_platform  }}    # [win]
    - cmake
  host:
    - python
    - llvmdev 7.0.0
    - vs2015_runtime # [win]
    # llvmdev is built with libz compression support
    - zlib           # [unix and not aarch64]
  run:
    - python >=3.6
    - vs2015_runtime # [win]
    - pytest

test:
  imports:
    - t2bc
    - t2bc.binding
  commands:
    - python -m pytest --pyargs t2bc

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
